// Generated by PeakRDL-regblock starting from JINJA templated  my_package_template.sv  file
`timescale 1ns/100ps

package {{hwif.package_name}};
    {{hwif.get_package_contents()|indent}}
endpackage
