ersion: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: dooku/requirements.txt

mkdocs:
  configuration: dooku/mkdocs.yml

jobs:
  pre_build:
    - GIT_ROOT=git rev-parse --show-toplevel
    - BUILD_ROOT=$READTHEDOCS_OUTPUT
