# Site name
site_name: rdnv

# Site metadata
site_author: Simone Corbetta

# Configuration
theme:
  name: terminal
  palette: gruvbox_dark

# Plugins
plugins:
  - search
  - badges

# Navigation
nav:
  - Home: 'index.md'
  - tatooine: 'tatooine.md'
  - organa: 'organa.md'
  - dooku: 'dooku.md'
  - dagobah: 'dagobah.md'
  - the_order: 'the_order.md'
