site_name: rdnv

plugins:
  - search
  - badges
  - macros:
      module_name: scripts/renders
      on_error_fail: true
      on_undefined: strict
      verbose: true

theme:
  name: terminal
  palette: gruvbox_dark
