# Site name
site_name: rdnv

# Site metadata
site_author: Simone Corbetta

# Source dir
docs_dir: src

# Target dir on minisite
site_dir: build

# Configuration
theme:
  name: terminal
  palette: gruvbox_dark

plugins:
  - search
  - badges
  - macros:
      module_name: scripts/renders
      on_error_fail: true
      on_undefined: strict
      verbose: true

extra:
  url_git_dooku: 'https://github.com/scorbetta/rdnv/blob/main/dooku'

nav:
  - Home: 'index.md'
  - dooku: 'dooku.md'
  - tatooine: 'tatooine.md'
  - organa: 'organa.md'
  - the_order: 'the_order.md'
