site_name: Nuclear Instruments Flea Market
site_description: A place of collectables - synthesizable RTL blocks, simulation primitives, tools, scripts and example designs
site_author: Nuclear Instruments
site_dir: public/

# Repository
repo_name: NI Cores
repo_url: https://gitlab.lanni/nuclear-instruments/ip-cores/ni-cores
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2022 Nuclear Instruments'

# Configuration
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  # favicon: assets/images/favicon.png
  logo: 'images/ni_logo_square_48px.png'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand

  icon:
    logo: 'images/ni_logo_square_48px.png'

# extra_css:
#   - css/styles.css
#   - css/dark-mode.css

# Plugins
plugins:
  - search
  - pdf-export:
      combined: true
  # - minify:
  #     minify_html: true
  - mermaid2:
      arguments:
        securityLevel: 'loose'
        # test if its __palette_1 (dark) or __palette_2 (light)
        # for mkdocs-material >=8.0.0
        theme: |

# Customization
# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/docker/getting-started

# Extensions
markdown_extensions:
  - admonition
  - markdown_wavedrom
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

extra_javascript:
    - extra/refresh_on_toggle_dark_light.js
    - extra/wavedrom/wavedrom.min.js
    - extra/wavedrom/default.js
    - extra/wavedrom/wavedrom_loader.js

# Page tree
nav:
    # Home page, with summary of contents
    - Home:
        - Summary: index.md

    # Main page for synthesis group
    - Synthesizable RTL blocks:
        - Table of Contents: syn.md
        - AXIL2NATIVE: modules/syn/AXIL2NATIVE.md
        - COMMON_CLOCK_FIFO: modules/syn/COMMON_CLOCK_FIFO.md
        - COUNTER: modules/syn/COUNTER.md
        - DDR_RING_BUFFER: modules/syn/DDR_RING_BUFFER.md
        - EDGE_DETECTOR: modules/syn/EDGE_DETECTOR.md
        - INDEPENDENT_CLOCK_FIFO: modules/syn/INDEPENDENT_CLOCK_FIFO.md
        - random_gaussian: modules/syn/random_gaussian.md
        - random_uniform: modules/syn/random_uniform.md
        - READ_ENGINE: modules/syn/READ_ENGINE.md
        - REGISTER: modules/syn/REGISTER.md
        - REGISTER_PIPELINE: modules/syn/REGISTER_PIPELINE.md
        - PARAMETRIC_DEMUX: modules/syn/PARAMETRIC_DEMUX.md
        - PARAMETRIC_MUX: modules/syn/PARAMETRIC_MUX.md
        - SDPRAM: modules/syn/SDPRAM.md
        - TDPRAM: modules/syn/TDPRAM.md

    # Main page for simulation group
    - RTL for simulation:
        - Table of Contents: sim.md
        - CLK_WIZARD: modules/sim/CLK_WIZARD.md

    # Main page for example designs
    - Example designs:
        - Table of Contents: exdes.md
        - Firmware Upgrade: modules/exdes/firmware_upgrade.md

    # Main page for tools
    - Tools:
        - Table of Contents: tools.md
        - GROGU: modules/tools/grogu.md

    # Main page for AXI4 design
    - AXI4:
        - Table of Contents: axi4.md
        - AXI4_PKG: modules/axi4/AXI4_PKG.md

