pages:
    image: registry.lanni/pages/mkdocs:latest
    script:
        - pip3 install -r requirements.txt
        - mkdocs build
        - manage-gitlab-badge
    when: always
    artifacts:
        paths:
            - public
